language: ruby
cache: bundler
rvm:
- 2.2
install:
- openssl aes-256-cbc -K $encrypted_06a58c71dec3_key -iv $encrypted_06a58c71dec3_iv
  -in ./travis-ci/accounts.enc -out ./travis-ci/accounts.json -d
- bundle install --jobs=3 --retry=3
deploy:
  provider: rubygems
  api_key:
    secure: CuHhTQZDEdCZ0V9C5PJwsWE2RWJRViJaHXwtCDcmWPkK6PXVoUmPfpZNRKKOWbSm3w8ibqYYoEMPv2x0rcMsnU4pSfZI80U+1dnTGnQ+kaL80gxyi65RXZK4sXHQ40p8t9QAFtX1XtCxKwas+cI92T0Y+IzPv9M3lXS+orac+3Gw/fLnLqgTUqAtE18WlSlcglXRo6/OJq1aiPiMFD9CC+TowvL6T45U0Yes7X9YEwVOSRnG8Ikxlkz6RQu3Wzevy1dMuUsFviR6OZa0PiDgXeh3+0UlNOvs+cPNpwXqHSW1cGZ551abKQ9vx6SLugjnRdR9PSveG1SE3xA1AnM0pQd3I/xTCoSZLT10AqyF43IM66+Tm9vEaIDoM33tR6/u13o0fPDNcaAgatUw8BF1fzfB0OW8RP6BPMQQqSfUpwtIK73uG6EqCFw1tDO9iBLKOywtJ6o+EcbbfiVepeiXftgM83i4BuGrTqwArbdD9pAImEx5xghB/fSkyjnZOTQA/MAw0qzDgEyTUkj7PmJhc5h8Az6GztpsZDBuv+NcAhe9vSFBUqHPumyllCSisIb9cBzMD8ASd9/P36ZxoixEmnyxKBLvuLoGc9swO2QYtmar6MZJkdWVNzk6Tfx2O/QvLgBydq5rOF6q+wLPh9pW/0ozz/YRi3ito6CqSxg0uIg=
  gem: square_connect
  on:
    branch: master
    repo: square/connect-ruby-sdk
