language: ruby
cache: bundler
rvm:
- 2.2
install:
- openssl aes-256-cbc -K $encrypted_6b4a5e8db617_key -iv $encrypted_6b4a5e8db617_iv -in ./travis-ci/accounts.enc -out ./travis-ci/accounts.json -d
- bundle install --jobs=3 --retry=3
